generateOres = true
blacklistedOres = ["bauxite", "iridium", "lead", "salt", "tin", "tungsten"]
spawnWithGuideBook = true
respawnWithGuideBook = false
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = false
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
